apiVersion: v1
kind: Service
metadata:
   name: k8s-hello-cloud-app-service
   labels:
      app: k8s-hello-cloud-app
spec:
   type: NodePort
   ports:
   - port: 8080
     nodePort: 30001
     protocol: TCP
   selector:
      app: k8s-hello-cloud-app