apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cloud-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-cloud-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: hello-cloud-app
      labels:
        app: hello-cloud-app
    spec:
      containers:
        - name: hello-cloud-app
          image: sai194/hello-cloud-app
          ports:
           - name: hello-cloud-app-port
             containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-cloud-app-service
spec:
  ports:
    - port: 8080
      nodePort: 31006
      targetPort: hello-cloud-app-port
      protocol: TCP
  selector:
    app: hello-cloud-app
  type: NodePort
